services:
  db:
    image: postgres:17-alpine
    environment:
      # Realised this is required to setup things properly using superuser for initial scripts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fhir
      SPRING_DATASOURCE_USERNAME: fhir
      SPRING_DATASOURCE_PASSWORD: fhir
      SPRING_DATASOURCE_HIKARI_CONNECTIONINITSQL: "SET search_path = fhir_ext, public"
volumes:
  pgdata:
