services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      # optional: seed scripts like in dev
      # - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: ghcr.io/${GITHUB_REPOSITORY}/fhir-server:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    env_file:
      - .env

volumes:
  pgdata:
